#!/bin/bash

set -e

rm -rf config.cache autom4te*.cache
#autoreconf --install

case `uname` in
    Darwin*)
        glibtoolize --automake ;;
    *)
        libtoolize --automake ;;
esac

aclocal
autoconf
autoheader
automake --add-missing
